apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i5xl
  namespace: phayes1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:542f112ec6571bde36044060597203d7412523d076bb9f7b87a2188df5c7266d
        name: my-nodejs
        resources: {}
status: {}
